// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUOoVMDYKmvMGyvUUVSIEH4ofLpB_BGNk',
    appId: '1:997325614711:web:9689df2c1e8548e52ae072',
    messagingSenderId: '997325614711',
    projectId: 'grocery-67a34',
    authDomain: 'grocery-67a34.firebaseapp.com',
    storageBucket: 'grocery-67a34.firebasestorage.app',
    measurementId: 'G-HT4PD67MQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt2pzitRKQ1hKPhICO5mpjQGEO0qM5J1c',
    appId: '1:997325614711:android:f7e15c25bd66bd4f2ae072',
    messagingSenderId: '997325614711',
    projectId: 'grocery-67a34',
    storageBucket: 'grocery-67a34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcsvGnwev9PlRBhJ-lFtdvUUiRXeGKVbo',
    appId: '1:997325614711:ios:1cfe90365d9a38262ae072',
    messagingSenderId: '997325614711',
    projectId: 'grocery-67a34',
    storageBucket: 'grocery-67a34.firebasestorage.app',
    iosBundleId: 'com.example.grocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcsvGnwev9PlRBhJ-lFtdvUUiRXeGKVbo',
    appId: '1:997325614711:ios:1cfe90365d9a38262ae072',
    messagingSenderId: '997325614711',
    projectId: 'grocery-67a34',
    storageBucket: 'grocery-67a34.firebasestorage.app',
    iosBundleId: 'com.example.grocery',
  );
}
